### ISSUE TITLE
Class 'Yajra\Disqus\DisqusServiceProvider::class' not found

### ISSUE THREAD

**Issue by reliq** [yajra/laravel-disqus#1]
Hello,

I ran into the following error upon running `php artisan vendor:publish --tag=disqus`:
## 

```
[Symfony\Component\Debug\Exception\FatalThrowableError]      
Class 'Yajra\Disqus\DisqusServiceProvider::class' not found
```

Please help.

**Comment by yajra** [comment]
Were you able to install the package using:

```
composer require yajra/laravel-disqus
```

Afterward, you need to register it on app.php or via provider.

**Comment by yajra** [comment]
You can also try publishing without tags:

``` php
php artisan vendor:publish
```

**Comment by reliq** [comment]
Hi Yajra,

I had installed the package using `composer require yajra/laravel-disqus` and published the assets with `php artisan vendor:publish` however I was still having the issue.

**Comment by yajra** [comment]
Can you try running composer show to verify that the package was installed?

```
$ composer show
```
