### ISSUE TITLE
Give my app login access to laravel-disqus

### ISSUE THREAD

**Issue by karthigamahe** [yajra/laravel-disqus#3]
Added laravel-disqus in my application but i doknow how to add my application login credential to  laravel-disques

**Comment by yajra** [comment]
Sorry for late response. You can add your credentials by setting the ff config on your env:

```php
DISQUS_ENABLED=true
DISQUS_USERNAME=your_username
```

**Comment by nanadjei** [comment]
@yajra Then you should add that to the readme

**Comment by yajra** [comment]
it's already on the [read me](https://github.com/yajra/laravel-disqus#config)?

**Comment by zotarelli** [comment]
In console of Chome DevTools, show this:
Uncaught DOMException: Blocked a frame with origin "https://disqus.com" from accessing a cross-origin frame.
Any suggestion to prevent this?
